export interface VistaPortafolioEstudiante{
  cedula:String;
  nombre:String;
  telefono:String;
  direccion:String;
  nombreFundacion:String;
  direccionFundacion:String;
  encargado:String;
  telefonoFundacion:String;
  cartaCompromiso:String;
  InformeInicio:String;
  controlAsistencia:String;
  informeFinal:String;
  controlCumplimiento:String;
  certificado:String;
  encuestaPercepcion:String;
  observaciones:String;
  estado:boolean;
}
